/* AUTO-GENERATED by tools/build-accessibility.mjs — do not edit by hand.
   Area accessibility ratings from OpenStreetMap, keyed by listing id. The
   Worker merges this into the feed (worker/lib/estateprime.mjs). Re-run the
   tool and redeploy when a listing is added or its coordinates change.
   Source: © OpenStreetMap contributors (ODbL). */
export const ACCESSIBILITY = {
	"8": {
		"transit": {
			"band": "good",
			"type": "bus",
			"m": 91
		},
		"errands": {
			"band": "excellent",
			"type": "bakery",
			"m": 4
		},
		"education": {
			"band": "excellent",
			"type": "school",
			"m": 108
		},
		"leisure": {
			"band": "excellent",
			"type": "park",
			"m": 89
		}
	},
	"15": {
		"transit": {
			"band": "good",
			"type": "bus",
			"m": 138
		},
		"errands": {
			"band": "limited",
			"type": null,
			"m": null
		},
		"education": {
			"band": "limited",
			"type": null,
			"m": null
		},
		"leisure": {
			"band": "limited",
			"type": null,
			"m": null
		}
	},
	"17": {
		"transit": {
			"band": "good",
			"type": "bus",
			"m": 20
		},
		"errands": {
			"band": "excellent",
			"type": "pharmacy",
			"m": 61
		},
		"education": {
			"band": "excellent",
			"type": "school",
			"m": 188
		},
		"leisure": {
			"band": "excellent",
			"type": "dining",
			"m": 6
		}
	},
	"18": {
		"transit": {
			"band": "excellent",
			"type": "metro",
			"m": 161
		},
		"errands": {
			"band": "excellent",
			"type": "supermarket",
			"m": 25
		},
		"education": {
			"band": "verygood",
			"type": "university",
			"m": 314
		},
		"leisure": {
			"band": "excellent",
			"type": "square",
			"m": 64
		}
	},
	"20": {
		"transit": {
			"band": "good",
			"type": "bus",
			"m": 280
		},
		"errands": {
			"band": "verygood",
			"type": "pharmacy",
			"m": 374
		},
		"education": {
			"band": "limited",
			"type": null,
			"m": null
		},
		"leisure": {
			"band": "limited",
			"type": null,
			"m": null
		}
	},
	"37": {
		"transit": {
			"band": "excellent",
			"type": "metro",
			"m": 196
		},
		"errands": {
			"band": "excellent",
			"type": "convenience",
			"m": 31
		},
		"education": {
			"band": "excellent",
			"type": "school",
			"m": 190
		},
		"leisure": {
			"band": "excellent",
			"type": "dining",
			"m": 28
		}
	},
	"61": {
		"transit": {
			"band": "good",
			"type": "bus",
			"m": 208
		},
		"errands": {
			"band": "excellent",
			"type": "supermarket",
			"m": 202
		},
		"education": {
			"band": "excellent",
			"type": "school",
			"m": 192
		},
		"leisure": {
			"band": "excellent",
			"type": "playground",
			"m": 145
		}
	},
	"66": {
		"transit": {
			"band": "good",
			"type": "bus",
			"m": 106
		},
		"errands": {
			"band": "excellent",
			"type": "pharmacy",
			"m": 231
		},
		"education": {
			"band": "excellent",
			"type": "school",
			"m": 159
		},
		"leisure": {
			"band": "excellent",
			"type": "park",
			"m": 234
		}
	},
	"71": {
		"transit": {
			"band": "good",
			"type": "bus",
			"m": 62
		},
		"errands": {
			"band": "excellent",
			"type": "pharmacy",
			"m": 125
		},
		"education": {
			"band": "excellent",
			"type": "school",
			"m": 225
		},
		"leisure": {
			"band": "excellent",
			"type": "dining",
			"m": 13
		}
	},
	"79": {
		"transit": {
			"band": "good",
			"type": "bus",
			"m": 204
		},
		"errands": {
			"band": "excellent",
			"type": "bakery",
			"m": 250
		},
		"education": {
			"band": "excellent",
			"type": "school",
			"m": 155
		},
		"leisure": {
			"band": "excellent",
			"type": "park",
			"m": 74
		}
	},
	"86": {
		"transit": {
			"band": "verygood",
			"type": "metro",
			"m": 314
		},
		"errands": {
			"band": "excellent",
			"type": "pharmacy",
			"m": 44
		},
		"education": {
			"band": "excellent",
			"type": "school",
			"m": 179
		},
		"leisure": {
			"band": "excellent",
			"type": "dining",
			"m": 20
		}
	},
	"95": {
		"transit": {
			"band": "good",
			"type": "bus",
			"m": 846
		},
		"errands": {
			"band": "limited",
			"type": null,
			"m": null
		},
		"education": {
			"band": "limited",
			"type": null,
			"m": null
		},
		"leisure": {
			"band": "limited",
			"type": null,
			"m": null
		}
	},
	"96": {
		"transit": {
			"band": "good",
			"type": "metro",
			"m": 688
		},
		"errands": {
			"band": "excellent",
			"type": "pharmacy",
			"m": 77
		},
		"education": {
			"band": "excellent",
			"type": "school",
			"m": 101
		},
		"leisure": {
			"band": "excellent",
			"type": "park",
			"m": 93
		}
	},
	"98": {
		"transit": {
			"band": "good",
			"type": "bus",
			"m": 303
		},
		"errands": {
			"band": "excellent",
			"type": "bakery",
			"m": 239
		},
		"education": {
			"band": "verygood",
			"type": "school",
			"m": 473
		},
		"leisure": {
			"band": "excellent",
			"type": "dining",
			"m": 54
		}
	},
	"99": {
		"transit": {
			"band": "good",
			"type": "metro",
			"m": 866
		},
		"errands": {
			"band": "excellent",
			"type": "pharmacy",
			"m": 244
		},
		"education": {
			"band": "excellent",
			"type": "school",
			"m": 193
		},
		"leisure": {
			"band": "excellent",
			"type": "gym",
			"m": 177
		}
	},
	"104": {
		"transit": {
			"band": "moderate",
			"type": "metro",
			"m": 1209
		},
		"errands": {
			"band": "excellent",
			"type": "pharmacy",
			"m": 227
		},
		"education": {
			"band": "excellent",
			"type": "school",
			"m": 189
		},
		"leisure": {
			"band": "excellent",
			"type": "park",
			"m": 119
		}
	},
	"107": {
		"transit": {
			"band": "good",
			"type": "bus",
			"m": 46
		},
		"errands": {
			"band": "excellent",
			"type": "convenience",
			"m": 293
		},
		"education": {
			"band": "verygood",
			"type": "kindergarten",
			"m": 339
		},
		"leisure": {
			"band": "excellent",
			"type": "dining",
			"m": 248
		}
	},
	"108": {
		"transit": {
			"band": "verygood",
			"type": "metro",
			"m": 332
		},
		"errands": {
			"band": "excellent",
			"type": "pharmacy",
			"m": 78
		},
		"education": {
			"band": "excellent",
			"type": "college",
			"m": 179
		},
		"leisure": {
			"band": "excellent",
			"type": "square",
			"m": 18
		}
	},
	"110": {
		"transit": {
			"band": "moderate",
			"type": "metro",
			"m": 1330
		},
		"errands": {
			"band": "excellent",
			"type": "convenience",
			"m": 111
		},
		"education": {
			"band": "excellent",
			"type": "school",
			"m": 229
		},
		"leisure": {
			"band": "excellent",
			"type": "park",
			"m": 75
		}
	},
	"111": {
		"transit": {
			"band": "good",
			"type": "metro",
			"m": 636
		},
		"errands": {
			"band": "excellent",
			"type": "pharmacy",
			"m": 25
		},
		"education": {
			"band": "excellent",
			"type": "school",
			"m": 68
		},
		"leisure": {
			"band": "excellent",
			"type": "park",
			"m": 210
		}
	},
	"112": {
		"transit": {
			"band": "good",
			"type": "bus",
			"m": 18
		},
		"errands": {
			"band": "verygood",
			"type": "convenience",
			"m": 303
		},
		"education": {
			"band": "verygood",
			"type": "college",
			"m": 528
		},
		"leisure": {
			"band": "verygood",
			"type": "dining",
			"m": 303
		}
	},
	"113": {
		"transit": {
			"band": "moderate",
			"type": "metro",
			"m": 1107
		},
		"errands": {
			"band": "excellent",
			"type": "pharmacy",
			"m": 95
		},
		"education": {
			"band": "excellent",
			"type": "school",
			"m": 34
		},
		"leisure": {
			"band": "excellent",
			"type": "park",
			"m": 45
		}
	}
};
