/* AUTO-GENERATED by tools/build-accessibility.mjs — do not edit by hand.
   Area accessibility ratings from OpenStreetMap, keyed by listing id. Each
   record carries the coordinates and profile it was computed for, so a rerun
   can tell what is still current. The Worker merges record.scores into the
   feed (worker/lib/estateprime.mjs). Re-run the tool and redeploy when
   listings are added, moved or retyped.
   Source: © OpenStreetMap contributors (ODbL). */
export const ACCESSIBILITY = {
	"8": {
		"lat": 40.727519,
		"lng": 22.91532,
		"profile": "workplace",
		"scores": {
			"transit": {
				"band": "good",
				"type": "bus",
				"m": 91
			},
			"dining": {
				"band": "excellent",
				"type": "restaurant",
				"m": 184,
				"also": [
					{
						"type": "bakery",
						"m": 4
					}
				]
			},
			"errands": {
				"band": "excellent",
				"type": "bakery",
				"m": 4,
				"also": [
					{
						"type": "pharmacy",
						"m": 122
					},
					{
						"type": "supermarket",
						"m": 135
					}
				]
			},
			"parking": {
				"band": "excellent",
				"type": "carpark",
				"m": 86
			}
		}
	},
	"15": {
		"lat": 40.444133,
		"lng": 23.020064,
		"profile": "home",
		"scores": {
			"transit": {
				"band": "good",
				"type": "bus",
				"m": 138
			},
			"errands": {
				"band": "limited",
				"type": null,
				"m": null
			},
			"education": {
				"band": "limited",
				"type": null,
				"m": null
			},
			"leisure": {
				"band": "limited",
				"type": null,
				"m": null
			}
		}
	},
	"17": {
		"lat": 40.731082,
		"lng": 22.91754,
		"profile": "home",
		"scores": {
			"transit": {
				"band": "good",
				"type": "bus",
				"m": 20
			},
			"errands": {
				"band": "excellent",
				"type": "pharmacy",
				"m": 61,
				"also": [
					{
						"type": "convenience",
						"m": 94
					},
					{
						"type": "bakery",
						"m": 349
					}
				]
			},
			"education": {
				"band": "excellent",
				"type": "school",
				"m": 188
			},
			"leisure": {
				"band": "verygood",
				"type": "dining",
				"m": 6,
				"also": [
					{
						"type": "playground",
						"m": 304
					},
					{
						"type": "park",
						"m": 305
					}
				]
			}
		}
	},
	"18": {
		"lat": 40.635791,
		"lng": 22.9432,
		"profile": "workplace",
		"scores": {
			"transit": {
				"band": "excellent",
				"type": "metro",
				"m": 161,
				"also": [
					{
						"type": "bus",
						"m": 55
					}
				]
			},
			"dining": {
				"band": "excellent",
				"type": "cafe",
				"m": 66,
				"also": [
					{
						"type": "bakery",
						"m": 39
					}
				]
			},
			"errands": {
				"band": "excellent",
				"type": "supermarket",
				"m": 25,
				"also": [
					{
						"type": "bakery",
						"m": 39
					},
					{
						"type": "pharmacy",
						"m": 40
					}
				]
			},
			"parking": {
				"band": "excellent",
				"type": "carpark",
				"m": 210
			}
		}
	},
	"61": {
		"lat": 40.639968721981,
		"lng": 22.858901023865,
		"profile": "home",
		"scores": {
			"transit": {
				"band": "good",
				"type": "bus",
				"m": 208
			},
			"errands": {
				"band": "verygood",
				"type": "supermarket",
				"m": 202,
				"also": [
					{
						"type": "pharmacy",
						"m": 308
					}
				]
			},
			"education": {
				"band": "excellent",
				"type": "school",
				"m": 192
			},
			"leisure": {
				"band": "moderate",
				"type": "playground",
				"m": 145,
				"also": [
					{
						"type": "park",
						"m": 613
					}
				]
			}
		}
	},
	"71": {
		"lat": 40.608984174358,
		"lng": 22.979578971863,
		"profile": "home",
		"scores": {
			"transit": {
				"band": "good",
				"type": "bus",
				"m": 62
			},
			"errands": {
				"band": "excellent",
				"type": "pharmacy",
				"m": 125,
				"also": [
					{
						"type": "bakery",
						"m": 165
					},
					{
						"type": "supermarket",
						"m": 173
					}
				]
			},
			"education": {
				"band": "excellent",
				"type": "school",
				"m": 225,
				"also": [
					{
						"type": "kindergarten",
						"m": 318
					}
				]
			},
			"leisure": {
				"band": "excellent",
				"type": "dining",
				"m": 13,
				"also": [
					{
						"type": "park",
						"m": 97
					},
					{
						"type": "gym",
						"m": 333
					}
				]
			}
		}
	},
	"79": {
		"lat": 40.673949681694,
		"lng": 22.902932167053,
		"profile": "home",
		"scores": {
			"transit": {
				"band": "good",
				"type": "bus",
				"m": 204
			},
			"errands": {
				"band": "excellent",
				"type": "bakery",
				"m": 250,
				"also": [
					{
						"type": "convenience",
						"m": 257
					},
					{
						"type": "pharmacy",
						"m": 262
					}
				]
			},
			"education": {
				"band": "excellent",
				"type": "school",
				"m": 155,
				"also": [
					{
						"type": "kindergarten",
						"m": 200
					}
				]
			},
			"leisure": {
				"band": "excellent",
				"type": "park",
				"m": 74,
				"also": [
					{
						"type": "dining",
						"m": 147
					},
					{
						"type": "gym",
						"m": 333
					}
				]
			}
		}
	},
	"86": {
		"lat": 40.6389578,
		"lng": 22.9388862,
		"profile": "home",
		"scores": {
			"transit": {
				"band": "verygood",
				"type": "metro",
				"m": 314,
				"also": [
					{
						"type": "bus",
						"m": 20
					}
				]
			},
			"errands": {
				"band": "excellent",
				"type": "pharmacy",
				"m": 44,
				"also": [
					{
						"type": "bakery",
						"m": 160
					},
					{
						"type": "supermarket",
						"m": 165
					}
				]
			},
			"education": {
				"band": "excellent",
				"type": "school",
				"m": 179,
				"also": [
					{
						"type": "university",
						"m": 194
					},
					{
						"type": "kindergarten",
						"m": 674
					}
				]
			},
			"leisure": {
				"band": "excellent",
				"type": "dining",
				"m": 20,
				"also": [
					{
						"type": "square",
						"m": 29
					},
					{
						"type": "gym",
						"m": 314
					}
				]
			}
		}
	},
	"95": {
		"lat": 40.714476284709,
		"lng": 22.876625061035,
		"profile": "logistics",
		"scores": {
			"transit": {
				"band": "good",
				"type": "bus",
				"m": 846
			},
			"roads": {
				"band": "verygood",
				"type": "junction",
				"m": 3172
			},
			"parking": {
				"band": "limited",
				"type": null,
				"m": null
			}
		}
	},
	"96": {
		"lat": 40.643273977425,
		"lng": 22.943615913391,
		"profile": "home",
		"scores": {
			"transit": {
				"band": "good",
				"type": "metro",
				"m": 685,
				"also": [
					{
						"type": "bus",
						"m": 143
					}
				]
			},
			"errands": {
				"band": "excellent",
				"type": "pharmacy",
				"m": 80,
				"also": [
					{
						"type": "supermarket",
						"m": 153
					},
					{
						"type": "bakery",
						"m": 385
					}
				]
			},
			"education": {
				"band": "excellent",
				"type": "school",
				"m": 100,
				"also": [
					{
						"type": "kindergarten",
						"m": 192
					},
					{
						"type": "university",
						"m": 684
					}
				]
			},
			"leisure": {
				"band": "excellent",
				"type": "park",
				"m": 88,
				"also": [
					{
						"type": "playground",
						"m": 193
					},
					{
						"type": "dining",
						"m": 259
					}
				]
			}
		}
	},
	"98": {
		"lat": 39.988234687451,
		"lng": 23.620176315308,
		"profile": "home",
		"scores": {
			"transit": {
				"band": "good",
				"type": "bus",
				"m": 303
			},
			"errands": {
				"band": "verygood",
				"type": "bakery",
				"m": 239,
				"also": [
					{
						"type": "convenience",
						"m": 281
					},
					{
						"type": "pharmacy",
						"m": 392
					}
				]
			},
			"education": {
				"band": "verygood",
				"type": "school",
				"m": 473,
				"also": [
					{
						"type": "kindergarten",
						"m": 1174
					}
				]
			},
			"leisure": {
				"band": "good",
				"type": "dining",
				"m": 54
			}
		}
	},
	"99": {
		"lat": 40.575936993646,
		"lng": 22.970148324966,
		"profile": "home",
		"scores": {
			"transit": {
				"band": "good",
				"type": "metro",
				"m": 861,
				"also": [
					{
						"type": "bus",
						"m": 76
					}
				]
			},
			"errands": {
				"band": "verygood",
				"type": "pharmacy",
				"m": 240,
				"also": [
					{
						"type": "bakery",
						"m": 280
					},
					{
						"type": "supermarket",
						"m": 428
					}
				]
			},
			"education": {
				"band": "excellent",
				"type": "school",
				"m": 187,
				"also": [
					{
						"type": "kindergarten",
						"m": 283
					},
					{
						"type": "university",
						"m": 1025
					}
				]
			},
			"leisure": {
				"band": "verygood",
				"type": "gym",
				"m": 165,
				"also": [
					{
						"type": "park",
						"m": 362
					},
					{
						"type": "dining",
						"m": 379
					}
				]
			}
		}
	},
	"104": {
		"lat": 40.581776881832,
		"lng": 22.968120574951,
		"profile": "home",
		"scores": {
			"transit": {
				"band": "good",
				"type": "bus",
				"m": 127,
				"also": [
					{
						"type": "metro",
						"m": 1200
					}
				]
			},
			"errands": {
				"band": "excellent",
				"type": "pharmacy",
				"m": 204,
				"also": [
					{
						"type": "convenience",
						"m": 269
					},
					{
						"type": "bakery",
						"m": 579
					}
				]
			},
			"education": {
				"band": "excellent",
				"type": "school",
				"m": 163,
				"also": [
					{
						"type": "kindergarten",
						"m": 183
					}
				]
			},
			"leisure": {
				"band": "excellent",
				"type": "park",
				"m": 93,
				"also": [
					{
						"type": "dining",
						"m": 292
					},
					{
						"type": "gym",
						"m": 430
					}
				]
			}
		}
	},
	"107": {
		"lat": 40.712768515281,
		"lng": 22.928488254547,
		"profile": "home",
		"scores": {
			"transit": {
				"band": "good",
				"type": "bus",
				"m": 46
			},
			"errands": {
				"band": "verygood",
				"type": "convenience",
				"m": 293,
				"also": [
					{
						"type": "pharmacy",
						"m": 309
					}
				]
			},
			"education": {
				"band": "verygood",
				"type": "kindergarten",
				"m": 339,
				"also": [
					{
						"type": "school",
						"m": 410
					},
					{
						"type": "college",
						"m": 791
					}
				]
			},
			"leisure": {
				"band": "good",
				"type": "dining",
				"m": 248,
				"also": [
					{
						"type": "gym",
						"m": 634
					}
				]
			}
		}
	},
	"108": {
		"lat": 40.63888185962,
		"lng": 22.938289046288,
		"profile": "home",
		"scores": {
			"transit": {
				"band": "verygood",
				"type": "metro",
				"m": 347,
				"also": [
					{
						"type": "bus",
						"m": 63
					}
				]
			},
			"errands": {
				"band": "excellent",
				"type": "pharmacy",
				"m": 94,
				"also": [
					{
						"type": "supermarket",
						"m": 137
					},
					{
						"type": "bakery",
						"m": 170
					}
				]
			},
			"education": {
				"band": "excellent",
				"type": "college",
				"m": 163,
				"also": [
					{
						"type": "school",
						"m": 230
					},
					{
						"type": "kindergarten",
						"m": 721
					}
				]
			},
			"leisure": {
				"band": "excellent",
				"type": "dining",
				"m": 24,
				"also": [
					{
						"type": "square",
						"m": 33
					},
					{
						"type": "gym",
						"m": 291
					}
				]
			}
		}
	},
	"110": {
		"lat": 40.6042951,
		"lng": 22.9740967,
		"profile": "logistics",
		"scores": {
			"transit": {
				"band": "good",
				"type": "bus",
				"m": 193,
				"also": [
					{
						"type": "metro",
						"m": 1304
					}
				]
			},
			"roads": {
				"band": "excellent",
				"type": "junction",
				"m": 1638
			},
			"parking": {
				"band": "excellent",
				"type": "carpark",
				"m": 247
			}
		}
	},
	"111": {
		"lat": 40.574456739406,
		"lng": 22.967938184738,
		"profile": "home",
		"scores": {
			"transit": {
				"band": "good",
				"type": "metro",
				"m": 618,
				"also": [
					{
						"type": "bus",
						"m": 36
					}
				]
			},
			"errands": {
				"band": "excellent",
				"type": "pharmacy",
				"m": 22,
				"also": [
					{
						"type": "bakery",
						"m": 121
					},
					{
						"type": "convenience",
						"m": 258
					}
				]
			},
			"education": {
				"band": "excellent",
				"type": "school",
				"m": 79,
				"also": [
					{
						"type": "kindergarten",
						"m": 113
					},
					{
						"type": "university",
						"m": 886
					}
				]
			},
			"leisure": {
				"band": "excellent",
				"type": "park",
				"m": 200,
				"also": [
					{
						"type": "playground",
						"m": 208
					},
					{
						"type": "dining",
						"m": 285
					}
				]
			}
		}
	},
	"112": {
		"lat": 40.702309505143,
		"lng": 22.927350997925,
		"profile": "logistics",
		"scores": {
			"transit": {
				"band": "good",
				"type": "bus",
				"m": 18
			},
			"roads": {
				"band": "excellent",
				"type": "junction",
				"m": 1359
			},
			"parking": {
				"band": "good",
				"type": "carpark",
				"m": 696
			}
		}
	},
	"113": {
		"lat": 40.582385450181,
		"lng": 22.966672182083,
		"profile": "home",
		"scores": {
			"transit": {
				"band": "good",
				"type": "bus",
				"m": 28,
				"also": [
					{
						"type": "metro",
						"m": 1108
					}
				]
			},
			"errands": {
				"band": "excellent",
				"type": "pharmacy",
				"m": 95,
				"also": [
					{
						"type": "convenience",
						"m": 164
					},
					{
						"type": "bakery",
						"m": 449
					}
				]
			},
			"education": {
				"band": "excellent",
				"type": "kindergarten",
				"m": 48,
				"also": [
					{
						"type": "school",
						"m": 50
					}
				]
			},
			"leisure": {
				"band": "excellent",
				"type": "park",
				"m": 36,
				"also": [
					{
						"type": "dining",
						"m": 155
					},
					{
						"type": "gym",
						"m": 328
					}
				]
			}
		}
	},
	"117": {
		"lat": 40.6216094,
		"lng": 22.9700508,
		"profile": "home",
		"scores": {
			"transit": {
				"band": "good",
				"type": "metro",
				"m": 629,
				"also": [
					{
						"type": "bus",
						"m": 76
					}
				]
			},
			"errands": {
				"band": "excellent",
				"type": "pharmacy",
				"m": 16,
				"also": [
					{
						"type": "supermarket",
						"m": 74
					},
					{
						"type": "bakery",
						"m": 106
					}
				]
			},
			"education": {
				"band": "excellent",
				"type": "school",
				"m": 132,
				"also": [
					{
						"type": "kindergarten",
						"m": 610
					},
					{
						"type": "university",
						"m": 700
					}
				]
			},
			"leisure": {
				"band": "excellent",
				"type": "dining",
				"m": 68,
				"also": [
					{
						"type": "playground",
						"m": 127
					},
					{
						"type": "park",
						"m": 137
					}
				]
			}
		}
	},
	"119": {
		"lat": 40.737378,
		"lng": 22.8765958,
		"profile": "home",
		"scores": {
			"transit": {
				"band": "good",
				"type": "bus",
				"m": 191
			},
			"errands": {
				"band": "good",
				"type": "pharmacy",
				"m": 143
			},
			"education": {
				"band": "limited",
				"type": null,
				"m": null
			},
			"leisure": {
				"band": "limited",
				"type": null,
				"m": null
			}
		}
	},
	"121": {
		"lat": 40.7309773,
		"lng": 22.9157893,
		"profile": "home",
		"scores": {
			"transit": {
				"band": "good",
				"type": "bus",
				"m": 98
			},
			"errands": {
				"band": "excellent",
				"type": "convenience",
				"m": 124,
				"also": [
					{
						"type": "pharmacy",
						"m": 187
					},
					{
						"type": "bakery",
						"m": 388
					}
				]
			},
			"education": {
				"band": "excellent",
				"type": "school",
				"m": 112
			},
			"leisure": {
				"band": "excellent",
				"type": "dining",
				"m": 108,
				"also": [
					{
						"type": "park",
						"m": 182
					},
					{
						"type": "playground",
						"m": 440
					}
				]
			}
		}
	},
	"122": {
		"lat": 40.7344283,
		"lng": 22.9170455,
		"profile": "home",
		"scores": {
			"transit": {
				"band": "good",
				"type": "bus",
				"m": 177
			},
			"errands": {
				"band": "verygood",
				"type": "pharmacy",
				"m": 325,
				"also": [
					{
						"type": "convenience",
						"m": 455
					},
					{
						"type": "bakery",
						"m": 556
					}
				]
			},
			"education": {
				"band": "excellent",
				"type": "school",
				"m": 64
			},
			"leisure": {
				"band": "verygood",
				"type": "park",
				"m": 263,
				"also": [
					{
						"type": "dining",
						"m": 371
					},
					{
						"type": "playground",
						"m": 588
					}
				]
			}
		}
	},
	"123": {
		"lat": 40.7274709,
		"lng": 22.9151674,
		"profile": "workplace",
		"scores": {
			"transit": {
				"band": "good",
				"type": "bus",
				"m": 80
			},
			"dining": {
				"band": "excellent",
				"type": "restaurant",
				"m": 174,
				"also": [
					{
						"type": "bakery",
						"m": 10
					}
				]
			},
			"errands": {
				"band": "excellent",
				"type": "bakery",
				"m": 10,
				"also": [
					{
						"type": "pharmacy",
						"m": 112
					},
					{
						"type": "supermarket",
						"m": 143
					}
				]
			},
			"parking": {
				"band": "excellent",
				"type": "carpark",
				"m": 72
			}
		}
	},
	"124": {
		"lat": 40.5983493,
		"lng": 22.9570809,
		"profile": "home",
		"scores": {
			"transit": {
				"band": "excellent",
				"type": "metro",
				"m": 294,
				"also": [
					{
						"type": "bus",
						"m": 193
					}
				]
			},
			"errands": {
				"band": "excellent",
				"type": "convenience",
				"m": 41,
				"also": [
					{
						"type": "pharmacy",
						"m": 47
					},
					{
						"type": "bakery",
						"m": 160
					}
				]
			},
			"education": {
				"band": "excellent",
				"type": "school",
				"m": 46,
				"also": [
					{
						"type": "kindergarten",
						"m": 248
					}
				]
			},
			"leisure": {
				"band": "excellent",
				"type": "park",
				"m": 90,
				"also": [
					{
						"type": "dining",
						"m": 119
					},
					{
						"type": "gym",
						"m": 327
					}
				]
			}
		}
	},
	"128": {
		"lat": 40.6443109,
		"lng": 22.9271422,
		"profile": "home",
		"scores": {
			"transit": {
				"band": "excellent",
				"type": "metro",
				"m": 82,
				"also": [
					{
						"type": "bus",
						"m": 54
					}
				]
			},
			"errands": {
				"band": "excellent",
				"type": "convenience",
				"m": 76,
				"also": [
					{
						"type": "pharmacy",
						"m": 104
					},
					{
						"type": "bakery",
						"m": 123
					}
				]
			},
			"education": {
				"band": "excellent",
				"type": "school",
				"m": 88,
				"also": [
					{
						"type": "university",
						"m": 176
					},
					{
						"type": "kindergarten",
						"m": 373
					}
				]
			},
			"leisure": {
				"band": "excellent",
				"type": "park",
				"m": 144,
				"also": [
					{
						"type": "dining",
						"m": 158
					},
					{
						"type": "playground",
						"m": 382
					}
				]
			}
		}
	},
	"131": {
		"lat": 40.6477614,
		"lng": 22.9528712,
		"profile": "home",
		"scores": {
			"transit": {
				"band": "good",
				"type": "bus",
				"m": 167,
				"also": [
					{
						"type": "metro",
						"m": 1456
					}
				]
			},
			"errands": {
				"band": "excellent",
				"type": "pharmacy",
				"m": 179,
				"also": [
					{
						"type": "bakery",
						"m": 202
					},
					{
						"type": "convenience",
						"m": 241
					}
				]
			},
			"education": {
				"band": "excellent",
				"type": "school",
				"m": 100,
				"also": [
					{
						"type": "kindergarten",
						"m": 278
					}
				]
			},
			"leisure": {
				"band": "verygood",
				"type": "playground",
				"m": 138,
				"also": [
					{
						"type": "park",
						"m": 338
					},
					{
						"type": "dining",
						"m": 361
					}
				]
			}
		}
	}
};
