/* AUTO-GENERATED by tools/build-accessibility.mjs — do not edit by hand.
   Area accessibility ratings from OpenStreetMap, keyed by listing id. Each
   record carries the coordinates and profile it was computed for, so a rerun
   can tell what is still current. The Worker merges record.scores into the
   feed (worker/lib/estateprime.mjs). Re-run the tool and redeploy when
   listings are added, moved or retyped.
   Source: © OpenStreetMap contributors (ODbL). */
export const ACCESSIBILITY = {
	"8": {
		"lat": 40.727519,
		"lng": 22.91532,
		"profile": "workplace",
		"scores": {
			"transit": {
				"band": "good",
				"type": "bus",
				"m": 91
			},
			"dining": {
				"band": "excellent",
				"type": "bakery",
				"m": 4
			},
			"errands": {
				"band": "excellent",
				"type": "bakery",
				"m": 4
			},
			"parking": {
				"band": "excellent",
				"type": "carpark",
				"m": 86
			}
		}
	},
	"15": {
		"lat": 40.444133,
		"lng": 23.020064,
		"profile": "home",
		"scores": {
			"transit": {
				"band": "good",
				"type": "bus",
				"m": 138
			},
			"errands": {
				"band": "limited",
				"type": null,
				"m": null
			},
			"education": {
				"band": "limited",
				"type": null,
				"m": null
			},
			"leisure": {
				"band": "limited",
				"type": null,
				"m": null
			}
		}
	},
	"17": {
		"lat": 40.731082,
		"lng": 22.91754,
		"profile": "home",
		"scores": {
			"transit": {
				"band": "good",
				"type": "bus",
				"m": 20
			},
			"errands": {
				"band": "excellent",
				"type": "pharmacy",
				"m": 61
			},
			"education": {
				"band": "excellent",
				"type": "school",
				"m": 188
			},
			"leisure": {
				"band": "excellent",
				"type": "dining",
				"m": 6
			}
		}
	},
	"18": {
		"lat": 40.635791,
		"lng": 22.9432,
		"profile": "workplace",
		"scores": {
			"transit": {
				"band": "excellent",
				"type": "metro",
				"m": 161
			},
			"dining": {
				"band": "excellent",
				"type": "bakery",
				"m": 39
			},
			"errands": {
				"band": "excellent",
				"type": "supermarket",
				"m": 25
			},
			"parking": {
				"band": "excellent",
				"type": "carpark",
				"m": 210
			}
		}
	},
	"61": {
		"lat": 40.639968721981,
		"lng": 22.858901023865,
		"profile": "home",
		"scores": {
			"transit": {
				"band": "good",
				"type": "bus",
				"m": 208
			},
			"errands": {
				"band": "excellent",
				"type": "supermarket",
				"m": 202
			},
			"education": {
				"band": "excellent",
				"type": "school",
				"m": 192
			},
			"leisure": {
				"band": "excellent",
				"type": "playground",
				"m": 145
			}
		}
	},
	"71": {
		"lat": 40.608984174358,
		"lng": 22.979578971863,
		"profile": "home",
		"scores": {
			"transit": {
				"band": "good",
				"type": "bus",
				"m": 62
			},
			"errands": {
				"band": "excellent",
				"type": "pharmacy",
				"m": 125
			},
			"education": {
				"band": "excellent",
				"type": "school",
				"m": 225
			},
			"leisure": {
				"band": "excellent",
				"type": "dining",
				"m": 13
			}
		}
	},
	"79": {
		"lat": 40.673949681694,
		"lng": 22.902932167053,
		"profile": "home",
		"scores": {
			"transit": {
				"band": "good",
				"type": "bus",
				"m": 204
			},
			"errands": {
				"band": "excellent",
				"type": "bakery",
				"m": 250
			},
			"education": {
				"band": "excellent",
				"type": "school",
				"m": 155
			},
			"leisure": {
				"band": "excellent",
				"type": "park",
				"m": 74
			}
		}
	},
	"86": {
		"lat": 40.6389578,
		"lng": 22.9388862,
		"profile": "home",
		"scores": {
			"transit": {
				"band": "verygood",
				"type": "metro",
				"m": 314
			},
			"errands": {
				"band": "excellent",
				"type": "pharmacy",
				"m": 44
			},
			"education": {
				"band": "excellent",
				"type": "school",
				"m": 179
			},
			"leisure": {
				"band": "excellent",
				"type": "dining",
				"m": 20
			}
		}
	},
	"95": {
		"lat": 40.714476284709,
		"lng": 22.876625061035,
		"profile": "logistics",
		"scores": {
			"transit": {
				"band": "good",
				"type": "bus",
				"m": 846
			},
			"roads": {
				"band": "verygood",
				"type": "junction",
				"m": 3172
			},
			"parking": {
				"band": "limited",
				"type": null,
				"m": null
			}
		}
	},
	"96": {
		"lat": 40.643273977425,
		"lng": 22.943615913391,
		"profile": "home",
		"scores": {
			"transit": {
				"band": "good",
				"type": "metro",
				"m": 685
			},
			"errands": {
				"band": "excellent",
				"type": "pharmacy",
				"m": 80
			},
			"education": {
				"band": "excellent",
				"type": "school",
				"m": 100
			},
			"leisure": {
				"band": "excellent",
				"type": "park",
				"m": 88
			}
		}
	},
	"98": {
		"lat": 39.988234687451,
		"lng": 23.620176315308,
		"profile": "home",
		"scores": {
			"transit": {
				"band": "good",
				"type": "bus",
				"m": 303
			},
			"errands": {
				"band": "excellent",
				"type": "bakery",
				"m": 239
			},
			"education": {
				"band": "verygood",
				"type": "school",
				"m": 473
			},
			"leisure": {
				"band": "excellent",
				"type": "dining",
				"m": 54
			}
		}
	},
	"99": {
		"lat": 40.575936993646,
		"lng": 22.970148324966,
		"profile": "home",
		"scores": {
			"transit": {
				"band": "good",
				"type": "metro",
				"m": 861
			},
			"errands": {
				"band": "excellent",
				"type": "pharmacy",
				"m": 240
			},
			"education": {
				"band": "excellent",
				"type": "school",
				"m": 187
			},
			"leisure": {
				"band": "excellent",
				"type": "gym",
				"m": 165
			}
		}
	},
	"104": {
		"lat": 40.581776881832,
		"lng": 22.968120574951,
		"profile": "home",
		"scores": {
			"transit": {
				"band": "moderate",
				"type": "metro",
				"m": 1200
			},
			"errands": {
				"band": "excellent",
				"type": "pharmacy",
				"m": 204
			},
			"education": {
				"band": "excellent",
				"type": "school",
				"m": 163
			},
			"leisure": {
				"band": "excellent",
				"type": "park",
				"m": 93
			}
		}
	},
	"107": {
		"lat": 40.712768515281,
		"lng": 22.928488254547,
		"profile": "home",
		"scores": {
			"transit": {
				"band": "good",
				"type": "bus",
				"m": 46
			},
			"errands": {
				"band": "excellent",
				"type": "convenience",
				"m": 293
			},
			"education": {
				"band": "verygood",
				"type": "kindergarten",
				"m": 339
			},
			"leisure": {
				"band": "excellent",
				"type": "dining",
				"m": 248
			}
		}
	},
	"108": {
		"lat": 40.63888185962,
		"lng": 22.938289046288,
		"profile": "home",
		"scores": {
			"transit": {
				"band": "verygood",
				"type": "metro",
				"m": 347
			},
			"errands": {
				"band": "excellent",
				"type": "pharmacy",
				"m": 94
			},
			"education": {
				"band": "excellent",
				"type": "college",
				"m": 163
			},
			"leisure": {
				"band": "excellent",
				"type": "dining",
				"m": 24
			}
		}
	},
	"110": {
		"lat": 40.6042951,
		"lng": 22.9740967,
		"profile": "logistics",
		"scores": {
			"transit": {
				"band": "moderate",
				"type": "metro",
				"m": 1304
			},
			"roads": {
				"band": "excellent",
				"type": "junction",
				"m": 1638
			},
			"parking": {
				"band": "excellent",
				"type": "carpark",
				"m": 247
			}
		}
	},
	"111": {
		"lat": 40.574456739406,
		"lng": 22.967938184738,
		"profile": "home",
		"scores": {
			"transit": {
				"band": "good",
				"type": "metro",
				"m": 618
			},
			"errands": {
				"band": "excellent",
				"type": "pharmacy",
				"m": 22
			},
			"education": {
				"band": "excellent",
				"type": "school",
				"m": 79
			},
			"leisure": {
				"band": "excellent",
				"type": "park",
				"m": 200
			}
		}
	},
	"112": {
		"lat": 40.702309505143,
		"lng": 22.927350997925,
		"profile": "logistics",
		"scores": {
			"transit": {
				"band": "good",
				"type": "bus",
				"m": 18
			},
			"roads": {
				"band": "excellent",
				"type": "junction",
				"m": 1359
			},
			"parking": {
				"band": "good",
				"type": "carpark",
				"m": 696
			}
		}
	},
	"113": {
		"lat": 40.582385450181,
		"lng": 22.966672182083,
		"profile": "home",
		"scores": {
			"transit": {
				"band": "moderate",
				"type": "metro",
				"m": 1108
			},
			"errands": {
				"band": "excellent",
				"type": "pharmacy",
				"m": 95
			},
			"education": {
				"band": "excellent",
				"type": "kindergarten",
				"m": 48
			},
			"leisure": {
				"band": "excellent",
				"type": "park",
				"m": 36
			}
		}
	},
	"116": {
		"lat": 40.6398527,
		"lng": 22.9609829,
		"profile": "home",
		"scores": {
			"transit": {
				"band": "moderate",
				"type": "metro",
				"m": 1145
			},
			"errands": {
				"band": "excellent",
				"type": "convenience",
				"m": 52
			},
			"education": {
				"band": "excellent",
				"type": "school",
				"m": 159
			},
			"leisure": {
				"band": "excellent",
				"type": "dining",
				"m": 84
			}
		}
	},
	"117": {
		"lat": 40.6216094,
		"lng": 22.9700508,
		"profile": "home",
		"scores": {
			"transit": {
				"band": "good",
				"type": "metro",
				"m": 629
			},
			"errands": {
				"band": "excellent",
				"type": "pharmacy",
				"m": 16
			},
			"education": {
				"band": "excellent",
				"type": "school",
				"m": 132
			},
			"leisure": {
				"band": "excellent",
				"type": "dining",
				"m": 68
			}
		}
	},
	"119": {
		"lat": 40.737378,
		"lng": 22.8765958,
		"profile": "home",
		"scores": {
			"transit": {
				"band": "good",
				"type": "bus",
				"m": 191
			},
			"errands": {
				"band": "excellent",
				"type": "pharmacy",
				"m": 143
			},
			"education": {
				"band": "limited",
				"type": null,
				"m": null
			},
			"leisure": {
				"band": "limited",
				"type": null,
				"m": null
			}
		}
	},
	"121": {
		"lat": 40.7309773,
		"lng": 22.9157893,
		"profile": "home",
		"scores": {
			"transit": {
				"band": "good",
				"type": "bus",
				"m": 98
			},
			"errands": {
				"band": "excellent",
				"type": "convenience",
				"m": 124
			},
			"education": {
				"band": "excellent",
				"type": "school",
				"m": 112
			},
			"leisure": {
				"band": "excellent",
				"type": "dining",
				"m": 108
			}
		}
	},
	"122": {
		"lat": 40.7344283,
		"lng": 22.9170455,
		"profile": "home",
		"scores": {
			"transit": {
				"band": "good",
				"type": "bus",
				"m": 177
			},
			"errands": {
				"band": "verygood",
				"type": "pharmacy",
				"m": 325
			},
			"education": {
				"band": "excellent",
				"type": "school",
				"m": 64
			},
			"leisure": {
				"band": "excellent",
				"type": "park",
				"m": 263
			}
		}
	},
	"123": {
		"lat": 40.7274709,
		"lng": 22.9151674,
		"profile": "workplace",
		"scores": {
			"transit": {
				"band": "good",
				"type": "bus",
				"m": 80
			},
			"dining": {
				"band": "excellent",
				"type": "bakery",
				"m": 10
			},
			"errands": {
				"band": "excellent",
				"type": "bakery",
				"m": 10
			},
			"parking": {
				"band": "excellent",
				"type": "carpark",
				"m": 72
			}
		}
	},
	"124": {
		"lat": 40.5983493,
		"lng": 22.9570809,
		"profile": "home",
		"scores": {
			"transit": {
				"band": "excellent",
				"type": "metro",
				"m": 294
			},
			"errands": {
				"band": "excellent",
				"type": "convenience",
				"m": 41
			},
			"education": {
				"band": "excellent",
				"type": "school",
				"m": 46
			},
			"leisure": {
				"band": "excellent",
				"type": "park",
				"m": 90
			}
		}
	},
	"128": {
		"lat": 40.6443109,
		"lng": 22.9271422,
		"profile": "home",
		"scores": {
			"transit": {
				"band": "excellent",
				"type": "metro",
				"m": 82
			},
			"errands": {
				"band": "excellent",
				"type": "convenience",
				"m": 76
			},
			"education": {
				"band": "excellent",
				"type": "school",
				"m": 88
			},
			"leisure": {
				"band": "excellent",
				"type": "park",
				"m": 144
			}
		}
	}
};
